# Agregar y quitar columnas

# ALTER TABLE <NOMBRE_TABLA>
# ADD COLUMN <NOMBRE_COLUMNA_NUEVA> <TIPO_DE_DATOS>(TAMANO);

# ALTER TABLE <NOMBRE_TABLE>
# DROP COLUMN <NOMBRE_COLUMNA_NUEVA>

##### DESARROLLLO ####

USE SAKILA;
CREATE TABLE KOI
SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM address;
SELECT * FROM KOI;

ALTER TABLE KOI
DROP COLUMN DISTRICT;
SELECT * FROM KOI;

ALTER TABLE KOI
ADD COLUMN NEW_DISTRICT VARCHAR(20);
SELECT * FROM KOI;

