USE Bodega;

CREATE TABLE EMPLEADOS(
ID INT NOT NULL PRIMARY KEY auto_increment,
APELLIDO VARCHAR(28),
NOMBRE VARCHAR(28),
EDAD INT NOT NULL,
CONSTRAINT EDAD CHECK (EDAD >= 18)
);

INSERT INTO EMPLEADOS (APELLIDO, NOMBRE, EDAD)
VALUES 
	("Gonzalez", "Jorge", 17)
;