# Truncar una tabla
# NO QUEREMOS ELIMNIAR UNA TABLA PERO SI TODOS LOS DATOS
## TRUNCATE <NOMBRE_TABLE>

### DESARROLLO ###

USE SAKILA;
CREATE TABLE KOI
SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM ADDRESS;
SELECT * FROM KOI;

TRUNCATE TABLE KOI;
SELECT * FROM KOI;